# You can use this file to create a conda environment for this pipeline:
#   conda env create -f psiclip_environment.yml
name: psiclip
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  ## bioconda packages, see above
  - fastqc=0.11.8
  - trim-galore=0.6.4
  - bowtie=1.2.3
  - star=2.7.3a
  - bedtools=2.28.0
  - sambamba=0.7.1
  - samtools=1.9
  - pysam=0.15.3
  - r-data.table=1.12.2
  - r-dplyr=0.8.3
  - r-ggplot2=3.2.1
  - r-base=3.6.1
  - r-lemon
  - r-scales
  - r-forcats
  - snakemake=5.13.0
  - bam-readcount
  - r-smoother
  - r-r.utils
  - r-ggthemes
  - r-zoo
  - r-cowplot
  - r-ggridges
  - r-plyr
  - r-quantreg
