# Define samples
samples:
    ctrl_no_FLAGed_protein_UV_ACT1_AC_exp21: ["../data/fastq/ERR3988022.fq.gz", "AC_actin_substrate"]
    ctrl_no_FLAGed_protein_UV_UBC4_AC_long_exp15: ["../data/fastq/ERR3988023.fq.gz", "AC_LONG_substrate"]
    ctrl_no_FLAGed_protein_UV_UBC4_AC_short_exp4_8: ["../data/fastq/ERR3988024.fq.gz", "AC_substrate"]
    ctrl_no_FLAGed_protein_UV_UBC4_WT_long_exp16: ["../data/fastq/ERR3988025.fq.gz", "WT_LONG_substrate"]
    ctrl_notag_Prp16_G378A_ACT1_WText20_DBR1_exp33: ["../data/fastq/ERR3988026.fq.gz", "ACT1_AC_ext20_substrate"]
    ctrl_notag_Prp16_G378A_ACT1_WText20_DBR1_exp43: ["../data/fastq/ERR3988027.fq.gz", "ACT1_AC_ext20_substrate"]
    ctrl_notag_Prp16_G378A_ACT1_WText40_DBR1_exp34: ["../data/fastq/ERR3988028.fq.gz", "ACT1_AC_ext40_substrate"]
    ctrl_notag_Prp16_G378A_ACT1_WText40_DBR1_exp45: ["../data/fastq/ERR3988029.fq.gz", "ACT1_AC_ext40_substrate"]
    ctrl_notag_Prp16_G378A_ACT1_WTextSL_DBR1_exp35: ["../data/fastq/ERR3988030.fq.gz", "ACT1_AC_extSL_substrate"]
    ctrl_notag_Prp16_G378A_ACT1_WTextSL_DBR1_exp44: ["../data/fastq/ERR3988031.fq.gz", "ACT1_AC_extSL_substrate"]
    ctrl_notag_Prp16_G378A_UBC4_AC_long_DBR1_exp23: ["../data/fastq/ERR3988032.fq.gz", "AC_LONG_substrate"]
    ctrl_notag_Prp16_G378A_UBC4_WT_long_DBR1_exp24: ["../data/fastq/ERR3988033.fq.gz", "WT_LONG_substrate"]
    ctrl_notag_Prp16_G378A_UV_UBC4_AC_long_exp30: ["../data/fastq/ERR3988034.fq.gz", "AC_LONG_substrate"]
    ctrl_notag_Prp16_G378A_UV_UBC4_WT_long_exp30: ["../data/fastq/ERR3988035.fq.gz", "WT_LONG_substrate"]
    ctrl_notag_Prp22_K512A_UBC4_dG_long_DBR1_exp37: ["../data/fastq/ERR3988036.fq.gz", "dG_UBC4_long_substrate"]
    ctrl_notag_Prp22_K512A_UBC4_dG_long_DBR1_exp38: ["../data/fastq/ERR3988037.fq.gz", "dG_UBC4_long_substrate"]
    ctrl_notag_Prp22_K512A_UBC4_WT54_DBR1_exp36: ["../data/fastq/ERR3988038.fq.gz", "WT_LS54_substrate"]
    ctrl_notag_Prp22_K512A_UV_UBC4_WT54_exp28: ["../data/fastq/ERR3988039.fq.gz", "WT_LS54_substrate"]
    ctrl_notag_UBC4_AC_long_DBR1_exp23: ["../data/fastq/ERR3988040.fq.gz", "AC_LONG_substrate"]
    ctrl_notag_UBC4_dG_long_DBR1_exp37: ["../data/fastq/ERR3988041.fq.gz", "dG_UBC4_long_substrate"]
    ctrl_notag_UBC4_dG_long_DBR1_exp38: ["../data/fastq/ERR3988042.fq.gz", "dG_UBC4_long_substrate"]
    ctrl_notag_UV_ACT1_AC_exp29: ["../data/fastq/ERR3988043.fq.gz", "AC_actin_substrate"]
    ctrl_notag_UV_ACT1_AC_Prp16_DBR1_exp32: ["../data/fastq/ERR3988044.fq.gz", "AC_actin_substrate"]
    ctrl_notag_UV_ACT1_AC_Prp16_exp31: ["../data/fastq/ERR3988045.fq.gz", "AC_actin_substrate"]
    ctrl_notag_UV_ACT1_AC_Prp16_G378A_DBR1_exp32: ["../data/fastq/ERR3988046.fq.gz", "AC_actin_substrate"]
    ctrl_notag_UV_ACT1_AC_Prp16_G378A_exp29: ["../data/fastq/ERR3988047.fq.gz", "AC_actin_substrate"]
    ctrl_notag_UV_ACT1_AC_Prp16_G378A_exp31: ["../data/fastq/ERR3988048.fq.gz", "AC_actin_substrate"]
    ctrl_notag_UV_ACT1_WT_Prp16_G378A_DBR1_exp32: ["../data/fastq/ERR3988049.fq.gz", "WT_actin_substrate"]
    ctrl_notag_UV_ACT1_WT_Prp16_G378A_exp29: ["../data/fastq/ERR3988050.fq.gz", "WT_actin_substrate"]
    ctrl_notag_UV_ACT1_WT_Prp16_G378A_exp31: ["../data/fastq/ERR3988051.fq.gz", "WT_actin_substrate"]
    ctrl_notag_UV_UBC4_AC_long_exp30: ["../data/fastq/ERR3988052.fq.gz", "AC_LONG_substrate"]
    ctrl_yeast_ACT1_3xMS2_Prp22_K512A_DBR1_exp_40: ["../data/fastq/ERR3988053.fq.gz", "ACT1_3xMS2_substrate"]
    ctrl_yeast_ACT1_3xMS2_Prp22_K512A_DBR1_exp_42: ["../data/fastq/ERR3988054.fq.gz", "ACT1_3xMS2_substrate"]
    ctrl_yeast_ACT1_dG_Prp22_DBR1_exp39: ["../data/fastq/ERR3988055.fq.gz", "ACT1_dG_substrate"]
    ctrl_yeast_ACT1_dG_Prp22_DBR1_exp41: ["../data/fastq/ERR3988056.fq.gz", "ACT1_dG_substrate"]
    ctrl_yeast_ACT1_dG_Prp22_DBR1_Prp18kd_exp46: ["../data/fastq/ERR3988057.fq.gz", "ACT1_dG_substrate"]
    ctrl_yeast_ACT1_dG_Prp22_DBR1_Prp18kd_exp47: ["../data/fastq/ERR3988058.fq.gz", "ACT1_dG_substrate"]
    ctrl_yeast_ACT1_dG_Prp22_K512A_DBR1_exp39: ["../data/fastq/ERR3988059.fq.gz", "ACT1_dG_substrate"]
    ctrl_yeast_ACT1_dG_Prp22_K512A_DBR1_exp41: ["../data/fastq/ERR3988060.fq.gz", "ACT1_dG_substrate"]
    ctrl_yeast_ACT1_dG_Prp22_K512A_DBR1_Prp18kd_exp50: ["../data/fastq/ERR3988061.fq.gz", "ACT1_dG_substrate"]
    ctrl_yeast_ACT1_dG_Prp22_K512A_DBR1_Prp18kd_exp51: ["../data/fastq/ERR3988062.fq.gz", "ACT1_dG_substrate"]
    ctrl_yeast_ACT1_WT_Prp22_DBR1_Prp18kd_exp48: ["../data/fastq/ERR3988063.fq.gz", "WT_actin_substrate"]
    ctrl_yeast_ACT1_WT_Prp22_DBR1_Prp18kd_exp49: ["../data/fastq/ERR3988064.fq.gz", "WT_actin_substrate"]
    ctrl_yeast_ACT1_WT_Prp22_K512A_DBR1_Prp18kd_exp52: ["../data/fastq/ERR3988065.fq.gz", "WT_actin_substrate"]
    ctrl_yeast_ACT1_WT_Prp22_K512A_DBR1_Prp18kd_exp53: ["../data/fastq/ERR3988066.fq.gz", "WT_actin_substrate"]
    noUV_SMB1_FLAG_ACT1_AC_exp21: ["../data/fastq/ERR3988067.fq.gz", "AC_actin_substrate"]
    noUV_SMB1_FLAG_UBC4_AC_short_exp8: ["../data/fastq/ERR3988068.fq.gz", "AC_substrate"]
    Prp16-FLAG_UBC4_AC_long_DBR1_exp23: ["../data/fastq/ERR3988069.fq.gz", "AC_LONG_substrate"]
    Prp16-G378A-FLAG_UBC4_WT_long_DBR1_exp24: ["../data/fastq/ERR3988070.fq.gz", "WT_LONG_substrate"]
    Prp16_FLAG_ACT1_AC_DBR1_exp32: ["../data/fastq/ERR3988071.fq.gz", "AC_actin_substrate"]
    Prp16_FLAG_ACT1_AC_exp29: ["../data/fastq/ERR3988072.fq.gz", "AC_actin_substrate"]
    Prp16_FLAG_ACT1_AC_exp31: ["../data/fastq/ERR3988073.fq.gz", "AC_actin_substrate"]
    PRP16_FLAG_UBC4_AC_long_exp15: ["../data/fastq/ERR3988074.fq.gz", "AC_LONG_substrate"]
    Prp16_FLAG_UBC4_AC_long_exp30: ["../data/fastq/ERR3988075.fq.gz", "AC_LONG_substrate"]
    Prp16_G378A-FLAG_ACT1_AC_DBR1_exp32: ["../data/fastq/ERR3988076.fq.gz", "AC_actin_substrate"]
    Prp16_G378A-FLAG_ACT1_AC_exp31: ["../data/fastq/ERR3988077.fq.gz", "AC_actin_substrate"]
    Prp16_G378A-FLAG_ACT1_WT_DBR1_exp32: ["../data/fastq/ERR3988078.fq.gz", "WT_actin_substrate"]
    Prp16_G378A-FLAG_ACT1_WT_exp31: ["../data/fastq/ERR3988079.fq.gz", "WT_actin_substrate"]
    Prp16_G378A-FLAG_ACT1_WText20_DBR1_exp33: ["../data/fastq/ERR3988080.fq.gz", "ACT1_AC_ext20_substrate"]
    Prp16_G378A-FLAG_ACT1_WText20_DBR1_exp43: ["../data/fastq/ERR3988081.fq.gz", "ACT1_AC_ext20_substrate"]
    Prp16_G378A-FLAG_ACT1_WText40_DBR1_exp34: ["../data/fastq/ERR3988082.fq.gz", "ACT1_AC_ext40_substrate"]
    Prp16_G378A-FLAG_ACT1_WText40_DBR1_exp44: ["../data/fastq/ERR3988083.fq.gz", "ACT1_AC_ext40_substrate"]
    Prp16_G378A-FLAG_ACT1_WTextSL_DBR1_exp35: ["../data/fastq/ERR3988084.fq.gz", "ACT1_AC_extSL_substrate"]
    Prp16_G378A-FLAG_ACT1_WTextSL_DBR1_exp45: ["../data/fastq/ERR3988085.fq.gz", "ACT1_AC_extSL_substrate"]
    Prp16_G378A-FLAG_UBC4_AC_long_DBR1_exp23: ["../data/fastq/ERR3988086.fq.gz", "AC_LONG_substrate"]
    Prp16_G378A_FLAG_ACT1_AC_exp29: ["../data/fastq/ERR3988087.fq.gz", "AC_actin_substrate"]
    Prp16_G378A_FLAG_ACT1_WT_exp29: ["../data/fastq/ERR3988088.fq.gz", "WT_actin_substrate"]
    PRP16_G378A_FLAG_UBC4_AC_long_exp15: ["../data/fastq/ERR3988089.fq.gz", "AC_LONG_substrate"]
    Prp16_G378A_FLAG_UBC4_AC_long_exp30: ["../data/fastq/ERR3988090.fq.gz", "AC_LONG_substrate"]
    PRP16_G378A_FLAG_UBC4_WT_long_exp16: ["../data/fastq/ERR3988091.fq.gz", "WT_LONG_substrate"]
    Prp16_G378A_FLAG_UBC4_WT_long_exp30: ["../data/fastq/ERR3988092.fq.gz", "WT_LONG_substrate"]
    Prp22-FLAG-His_yeast_ACT1_dG_Prp22_DBR1_exp39: ["../data/fastq/ERR3988093.fq.gz", "ACT1_dG_substrate"]
    Prp22-FLAG-His_yeast_ACT1_dG_Prp22_DBR1_exp41: ["../data/fastq/ERR3988094.fq.gz", "ACT1_dG_substrate"]
    Prp22-FLAG_UBC4_dG_long_DBR1_exp37: ["../data/fastq/ERR3988095.fq.gz", "dG_UBC4_long_substrate"]
    Prp22-FLAG_UBC4_dG_long_DBR1_exp38: ["../data/fastq/ERR3988096.fq.gz", "dG_UBC4_long_substrate"]
    Prp22_K512A_FLAG_UBC4_WT54_Prp22_K512A_exp28: ["../data/fastq/ERR3988097.fq.gz", "WT_LS54_substrate"]
    Prp22_K512A_yeast_ACT1_dG_DBR1_Prp18kd_exp50: ["../data/fastq/ERR3988098.fq.gz", "ACT1_dG_substrate"]
    Prp22_K512A_yeast_ACT1_dG_DBR1_Prp18kd_exp51: ["../data/fastq/ERR3988099.fq.gz", "ACT1_dG_substrate"]
    Prp22_K512A_yeast_ACT1_WT_DBR1_Prp18kd_exp52: ["../data/fastq/ERR3988100.fq.gz", "WT_actin_substrate"]
    Prp22_K512A_yeast_ACT1_WT_DBR1_Prp18kd_exp53: ["../data/fastq/ERR3988101.fq.gz", "WT_actin_substrate"]
    Prp22_K521A-FLAG-His_yeast_ACT1_3xMS2_Prp22_K512A_DBR1_exp40: ["../data/fastq/ERR3988102.fq.gz", "ACT1_3xMS2_substrate"]
    Prp22_K521A-FLAG-His_yeast_ACT1_3xMS2_Prp22_K512A_DBR1_exp42: ["../data/fastq/ERR3988103.fq.gz", "ACT1_3xMS2_substrate"]
    Prp22_K521A-FLAG-His_yeast_ACT1_dG_Prp22_K512A_DBR1_exp39: ["../data/fastq/ERR3988104.fq.gz", "ACT1_dG_substrate"]
    Prp22_K521A-FLAG-His_yeast_ACT1_dG_Prp22_K512A_DBR1_exp41: ["../data/fastq/ERR3988105.fq.gz", "ACT1_dG_substrate"]
    Prp22_K521A-FLAG_UBC4_dG_long_DBR1_exp37: ["../data/fastq/ERR3988106.fq.gz", "dG_UBC4_long_substrate"]
    Prp22_K521A-FLAG_UBC4_dG_long_DBR1_exp38: ["../data/fastq/ERR3988107.fq.gz", "dG_UBC4_long_substrate"]
    Prp22_K521A-FLAG_UBC4_WT54_DBR1_exp36: ["../data/fastq/ERR3988108.fq.gz", "WT_LS54_substrate"]
    Prp22_yeast_ACT1_dG_DBR1_Prp18kd_exp46: ["../data/fastq/ERR3988109.fq.gz", "ACT1_dG_substrate"]
    Prp22_yeast_ACT1_dG_DBR1_Prp18kd_exp47: ["../data/fastq/ERR3988110.fq.gz", "ACT1_dG_substrate"]
    Prp22_yeast_ACT1_WT_DBR1_Prp18kd_exp48: ["../data/fastq/ERR3988111.fq.gz", "WT_actin_substrate"]
    Prp22_yeast_ACT1_WT_DBR1_Prp18kd_exp49: ["../data/fastq/ERR3988112.fq.gz", "WT_actin_substrate"]
    SMB1_FLAG_ACT1_AC_exp21: ["../data/fastq/ERR3988113.fq.gz", "AC_actin_substrate"]
    SMB1_FLAG_His_UBC4_AC_short_exp8: ["../data/fastq/ERR3988114.fq.gz", "AC_substrate"]

############## Files for index generation and mapping #############

#ACT1_3xMS2
ACT1_3xMS2_genome: substrate-omes/ACT1_WT-MS2.fa
ACT1_3xMS2_gtf_file: substrate-omes/ACT1_WT-MS2.final.gtf

#ACT1_dG
ACT1_dG_genome: substrate-omes/ACT1_dG.fa
ACT1_dG_gtf_file: substrate-omes/ACT1_dG.final.gtf

#ACT1_AC_ext20
ACT1_AC_ext20_genome: substrate-omes/ACT1_ext20.fa 
ACT1_AC_ext20_gtf_file: substrate-omes/ACT1_ext20.final.gtf

#ACT1_AC_ext40_substrate
ACT1_AC_ext40_substrate_genome: substrate-omes/ACT1_ext40.fa
ACT1_AC_ext40_substrate_gtf_file: substrate-omes/ACT1_ext40.final.gtf

#ACT1_AC_extSL_substrate
ACT1_AC_extSL_substrate_genome: substrate-omes/ACT1_extSL.fa
ACT1_AC_extSL_substrate_gtf_file: substrate-omes/ACT1_extSL.final.gtf

# AC substrate
AC_genome: substrate-omes/AC_ome.2.fa
AC_gtf_file: substrate-omes/AC_sub.final.gtf

# AC substrate with a longer second exon
AC_LONG_genome: substrate-omes/AC_long_ome.fa
AC_LONG_gtf_file: substrate-omes/AC_sub_long.final.gtf

# WT substrate long exon 2
WT_LONG_genome: substrate-omes/WT_long_ome.fa
WT_LONG_gtf_file: substrate-omes/WT_sub_long.final.gtf

# DG substrate
DG_genome: substrate-omes/dG_ome.fa
DG_gtf_file: substrate-omes/dG_sub.final.gtf

#dG_UBC4_long_substrate
DG_LONG_genome: substrate-omes/dG_long_ome.fa
DG_LONG_gtf_file: substrate-omes/dG_long_sub.final.gtf

# WT 1400 substrate
WT1400_genome: substrate-omes/WT1400_ome.fa
WT1400_gtf_file: substrate-omes/WT1400_sub.final.gtf

# WT LS54 substrate
WTLS54_genome: substrate-omes/WTLS54_ome.fa
WTLS54_gtf_file: substrate-omes/WTLS54_sub.final.gtf

# Actin WT substrate
WT_actin_genome: substrate-omes/WT_actin.fa
WT_actin_gtf_file: substrate-omes/WT_actin.final.gtf

# Actin AC substrate
AC_actin_genome: substrate-omes/AC_actin.fa
AC_actin_gtf_file: substrate-omes/AC_actin.final.gtf

# Yeast genome
yeast_genome: yeast-genome/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz
yeast_gtf_file: yeast-genome/Saccharomyces_cerevisiae.R64-1-1.99.gtf.gz

# Parameters for key steps
trim_galore_params: AGATCGGAAGGCGGTTCAG # Provide 3' adaptor sequence or use True to use default illumina
